homebrew_packages:
- awk
- bash
- bat
- beeftornado/rmtree
- clang-format
- cmake
- dos2unix
- fd
- felixkratz/formulae/sketchybar
- fzf
- gdb
- git
- gnutls
- htop
- ifstat
- imagemagick
- jq
- koekeishiya/formulae/skhd
- koekeishiya/formulae/yabai
- lazygit
- libgcrypt
- llvm
- lsd
- lua
- neovim
- node
- nvm
- pandoc
- pfetch
- pidof
- python
- python@3.10
- qmk/qmk/qmk
- ripgrep
- ruby
- sphinx-doc
- starship
- stow
- task
- taskwarrior-tui
- tmux
- tree
- vim
- wakeonlan
- wget
- yaml-language-server
- yarn

homebrew_casks:
- alacritty
- appcleaner
- android-platform-tools
- calibre
- firefox
- font-fira-code-nerd-font
- font-fira-mono-nerd-font
- font-iosevka-nerd-font
- font-jetbrains-mono-nerd-font
- font-meslo-lg-nerd-font
- font-victor-mono-nerd-font
- google-chrome
- iterm2
- macpass
- qmk-toolbox
- rectangle
- the-unarchiver
- ticktick
- transmission
- via
- vlc
- vscodium
