- name: Include variables
  include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Install apt packages
  apt:
    name: '{{ apt_packages }}'
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install homebrew packages
  homebrew:
    name: '{{ homebrew_packages }}'
    state: latest
  when: ansible_distribution == "MacOSX"
